import json
import sys
import os

def step3DataContractGen(digest, nifs_secondary, r_U_secondary, l_U_secondary):
    # TODO: Fill this in
    return ""

vk_file = sys.argv[1]
if not os.path.exists(vk_file):
    print("verifier-key (json) input file is missing")
    exit(1)

vk_f = open(os.path.basename(vk_file))
vk_data = json.load(vk_f)
digest = vk_data["digest"]

proof_file = sys.argv[2]
if not os.path.exists(proof_file):
    print("compressed snark (json) input file is missing")
    exit(1)

proof_f = open(os.path.basename(proof_file))
proof_data = json.load(proof_f)
nifs_secondary = proof_data["nifs_secondary"]
r_U_secondary = proof_data["r_U_secondary"]
l_U_secondary = proof_data["l_U_secondary"]

header = "// SPDX-License-Identifier: Apache-2.0\n"
header += f"// Do not change manually. This contract has been auto-generated by {sys.argv[0]}\n"
header += "pragma solidity ^0.8.0;\n"

function_def =  "function returnData() public pure returns (TODO) {\n"
function_def += step3DataContractGen(digest, nifs_secondary, r_U_secondary, l_U_secondary) 
function_def += "}\n"

contract_body = "library Step3Data { \n"
contract_body += function_def
contract_body += "}\n"
