// SPDX-License-Identifier: Apache-2.0
// Do not change manually. This contract has been auto-generated by src/verifier/step3/step3-data-contract-gen.py
pragma solidity ^0.8.16;

import "src/Utilities.sol";

library Step3Data {
    /* This function returns the following results in order:
    * pp_digest, NIFS instance, r_U comm_W, r_U comm_E, r_U X, r_U u
    * l_u comm_W, l_u X
    */
    function returnPrimaryData()
        public
        pure
        returns (uint256, bytes32, uint256, uint256, uint256[] memory, uint256, uint256, uint256[] memory)
    {
        uint8[32] memory nifs_array;
        nifs_array[0] = 129;
        nifs_array[1] = 78;
        nifs_array[2] = 43;
        nifs_array[3] = 114;
        nifs_array[4] = 14;
        nifs_array[5] = 217;
        nifs_array[6] = 55;
        nifs_array[7] = 0;
        nifs_array[8] = 141;
        nifs_array[9] = 134;
        nifs_array[10] = 81;
        nifs_array[11] = 102;
        nifs_array[12] = 170;
        nifs_array[13] = 237;
        nifs_array[14] = 6;
        nifs_array[15] = 198;
        nifs_array[16] = 55;
        nifs_array[17] = 200;
        nifs_array[18] = 187;
        nifs_array[19] = 76;
        nifs_array[20] = 24;
        nifs_array[21] = 102;
        nifs_array[22] = 243;
        nifs_array[23] = 155;
        nifs_array[24] = 138;
        nifs_array[25] = 115;
        nifs_array[26] = 129;
        nifs_array[27] = 71;
        nifs_array[28] = 160;
        nifs_array[29] = 43;
        nifs_array[30] = 56;
        nifs_array[31] = 24;
        bytes32 nifs = Field.uint8ArrayToBytes32(nifs_array);
        uint256 r_U_comm_W = 0x1b76eba7530b994f67164777aae37817048460b0849628e9981dcf9b39a431ac;
        uint256 r_U_comm_E = 0xa92e17aa8e3e813b25db0821f1d0cf57318ace70937d7ccb2b60e68e2967fdbb;
        uint256[] memory r_U_X = new uint256[](2);
        r_U_X[0] = 0x1afccc8b4eaa3bc1718194359f53d11f56c9dcbc44b435dd8acd4055542bf541;
        r_U_X[1] = 0x0b3f6387ca3de17a52ca09ab0ec108a3c793cb930f745f5f788507aa4e5e18e9;
        uint256 r_U_u = 0x00000000000000000000000000000000cc6b54563b3f5aefcc072ff891dfb5eb;
        uint256 l_u_comm_W = 0x73cb2576d50f1f5e74dce3cf18a48deb5ee483e870d5e8e8a8605b07dfe1920c;
        uint256[] memory l_u_X = new uint256[](2);
        l_u_X[0] = 0x02d41d38dd6cad4a4b3d3c0d10aa819c7649c0eba9400203531f52d1fb6275ca;
        l_u_X[1] = 0x038221039f55af9c7bc62b80657320a9d1618bc5877a07a16e6e206a52234a32;
        return (
            0x00f3d576562a91495d3763cc5d7394b640087c280c3870af2dbccacad38ea1dc,
            nifs,
            r_U_comm_W,
            r_U_comm_E,
            r_U_X,
            r_U_u,
            l_u_comm_W,
            l_u_X
        );
    }

    /* This function returns the following results in order:
    * pp_digest, NIFS instance, r_U comm_W, r_U comm_E, r_U X, r_U u
    * l_u comm_W, l_u X
    */
    function returnSecondaryData()
        public
        pure
        returns (uint256, bytes32, uint256, uint256, uint256[] memory, uint256, uint256, uint256[] memory)
    {
        uint8[32] memory nifs_array;
        nifs_array[0] = 51;
        nifs_array[1] = 28;
        nifs_array[2] = 184;
        nifs_array[3] = 191;
        nifs_array[4] = 145;
        nifs_array[5] = 149;
        nifs_array[6] = 208;
        nifs_array[7] = 155;
        nifs_array[8] = 200;
        nifs_array[9] = 88;
        nifs_array[10] = 188;
        nifs_array[11] = 40;
        nifs_array[12] = 1;
        nifs_array[13] = 24;
        nifs_array[14] = 67;
        nifs_array[15] = 125;
        nifs_array[16] = 209;
        nifs_array[17] = 153;
        nifs_array[18] = 46;
        nifs_array[19] = 23;
        nifs_array[20] = 49;
        nifs_array[21] = 243;
        nifs_array[22] = 244;
        nifs_array[23] = 155;
        nifs_array[24] = 67;
        nifs_array[25] = 33;
        nifs_array[26] = 24;
        nifs_array[27] = 58;
        nifs_array[28] = 215;
        nifs_array[29] = 175;
        nifs_array[30] = 103;
        nifs_array[31] = 6;
        bytes32 nifs = Field.uint8ArrayToBytes32(nifs_array);
        uint256 r_U_comm_W = 0xfeb641951cb4c21bdc4906f57b46942c0ae22b6c852266f64a4e0b77de5c4432;
        uint256 r_U_comm_E = 0x8412865c490c9e1219066e4e257f3bb28e00db31736251586c86197f6ec866a2;
        uint256[] memory r_U_X = new uint256[](2);
        r_U_X[0] = 0x107b0ae1735bf84de833f1d79b14709113a2e59ba6b3e153d39a7ed25e72441a;
        r_U_X[1] = 0x171bab5abc567e31000f484e5e7dcc5e5abb57e3760e3b2d338a2aa0a0f31d23;
        uint256 r_U_u = 0x000000000000000000000000000000011804c228713446acb2495858f1571f61;
        uint256 l_u_comm_W = 0xd07c3b4dd208f32a9e2d16213a976ad6f61dbdba7760478a85726dee9475e989;
        uint256[] memory l_u_X = new uint256[](2);
        l_u_X[0] = 0x038221039f55af9c7bc62b80657320a9d1618bc5877a07a16e6e206a52234a32;
        l_u_X[1] = 0x03ce69bf1e04bd1b76a92ef407cc40b41e47a382b064122a8bca3e39144e0cae;
        return (
            0x03b750843494b51c2e24cd02b764d3fd73901b6f64328d97ffef6ee95168bd34,
            nifs,
            r_U_comm_W,
            r_U_comm_E,
            r_U_X,
            r_U_u,
            l_u_comm_W,
            l_u_X
        );
    }
}
